### ISSUE TITLE
Remove `@`when renaming captures

### ISSUE THREAD

**Issue by ValdezFOmar** [ribru17/ts_query_ls#1]
When renaming a capture, the `@` symbol is included in the new name prompt but the server returns an error because the `@` is not allowed according to this regex:

https://github.com/ribru17/ts_query_ls/blob/666c6cb960f361c2b1c2d175918ac0d6b71067cb/src/main.rs#L670

I think the problem is on this line:

https://github.com/ribru17/ts_query_ls/blob/666c6cb960f361c2b1c2d175918ac0d6b71067cb/src/main.rs#L667

Since `(capture)` contains `"@"` as anonymous node (should probably just capture `(identifier)`?):

```
(capture
  "@"
  name: (identifier))
```

### Screenshots

![image](https://github.com/user-attachments/assets/48351a8d-2c3a-4608-b0e0-9f113a313cac)

![image](https://github.com/user-attachments/assets/ea6e8832-cc4d-4ff5-9b5b-90eb884f3205)

**Comment by ribru17** [comment]
Ah, thanks. This is somewhat intentional since the server omits @ sign (it assumes captures always start with it). Can you confirm that renaming works properly if you do not specify "@" in the beginning of the new name?

**Comment by ValdezFOmar** [comment]
> Ah, thanks. This is somewhat intentional since the server omits @ sign (it assumes captures always start with it). Can you confirm that renaming works properly if you do not specify "@" in the beginning of the new name?

Yeah it works, my point is that the server should not include that character if its going to reject it anyways.

> But this is at least kind of confusing. Maybe I should add a rule to ignore the first character of the new name if it is "@"?

Or just include the character as part of the new name, but you do you.

**Comment by ribru17** [comment]
> Or just don't include the character as part of the new name, but you do you.

Yes, this is exactly what I meant :smile:
