### ISSUE TITLE
ts_query_ls is not in nixpkgs 24.11. Only in unstable.

### ISSUE THREAD

**Issue by ArkieSoft** [ribru17/ts_query_ls#20]
I ran an update with NixVIM and it is popping up this error ```error: ts_query_ls cannot be found in pkgs```. I checked nixpkgs and it is only in unstable branch and not the main 24.11 branch. Is this a recent change? Or did NixVIM mess something up and I should take it to them?

**Comment by ribru17** [comment]
I think this is normal. The package was added to nix quite recently, maybe a month ago. Not sure how often master gets merged into the stable releases but I don't think it's unexpected to not be there. You'll probably have to wait some time or use unstable to access it now
